### ISSUE TITLE
scipy

### ISSUE THREAD

**Issue by Bucchiman** [Bucchiman/py#5]
# toDo
    - [] ファイル入出力: scipy.io
    - [] 特殊関数: scipy.special
    - [] 線形代数演算: scipy.linalg
    - [] 高速 Fourier 変換: scipy.fftpack
    - [] 最適化とフィット: scipy.optimize
    - [] 統計と乱数: scipy.stats
    - [] 補間: scipy.interpolate
    - [] 数値積分: scipy.integrate
    - [] 信号解析: scipy.signal
    - [] 画像処理: scipy.ndimage
    - [] 科学技術計算の総合演習

# Reference
- http://www.turbare.net/transl/scipy-lecture-notes/intro/scipy.html
